<a href="https://colab.research.google.com/github/nsriniva/DS-Unit-1-Sprint-2-Statistics/blob/master/module1/LS_DSPT9_121_t_tests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## *Data Science Unit 1 Sprint 2 Module 1*

# T-tests (Inferential Statistics)

## Learning Objectives
- Student can explain the purpose of and be able to identify opportunities and applications for t-tests
- Student can set up and run a one-sample t test on a sample
- Student can set up and run a two-sample t test comparing two samples
- Studen can use a p-value to draw the correct conclusion about the null and alternative hypothesis and give a written conclusion

## What is Descriptive Statistics?

<https://statistics.laerd.com/statistical-guides/descriptive-inferential-statistics.php>

In [ ]:
import pandas as pd
df = pd.DataFrame({'a': [1,2,3,4,5], 'b': [2,4,6,8,10]})
df.head()

a   b
0  1   2
1  2   4
2  3   6
3  4   8
4  5  10

In [ ]:
# How can we quickly look at some descriptive statistics of the above dataframe?
df.describe()



a          b
count  5.000000   5.000000
mean   3.000000   6.000000
std    1.581139   3.162278
min    1.000000   2.000000
25%    2.000000   4.000000
50%    3.000000   6.000000
75%    4.000000   8.000000
max    5.000000  10.000000

## What is Inferential Statistics?

<https://slideplayer.com/slide/5130463/16/images/2/Statistical+Inference.jpg>

## Hypothesis Testing (T-Tests)

Drawing conclusions based on probability in the face of randomness



Is the sample reflective of our concept of the population?

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
# Coinflips example - What is the population?
coinflips = np.random.binomial(n=1, p=.5, size = 10)

coinflips.mean()

#population is every possible coinflip that could take place with a fair coin
#if my flips -> inf


0.6

If we repeat the sampling why does our estimate of the mean move around so much? 

In [ ]:
# Coinflips example - See the implications of randomness
coinflips = np.random.binomial(n=1, p=.5, size = 1000000)
coinflips.mean()

0.500047

What happens as I increase the sample size? The sample mean deviates less from the population mean?

In [ ]:
# More Information -> Greater Confidence in the face of randomness

![Standard Error of the Sample  Mean](https://jungminded.weebly.com/uploads/1/3/5/8/13582285/7285766_orig.jpeg?160)

**Conclusion: As our sample size goes up, our estimates (of the mean in this case) get more precise, allowing us to infer things about the population with greater confidence.**

Standard Deviation is a measure of spread. Standard error is also a measure of spread. The SE represents the SD for samples.


## One Sample T-test

What if I didn't have a fair coin?

Comparing information from a sample against our concept of the population.

![One Sample T Statistic](https://www.statisticshowto.com/wp-content/uploads/2015/09/t-score.jpg)

## The T-test Process:

In [ ]:
from scipy import stats

In [ ]:
# Lets use a tool called a t-test to test if this is a fair coin or not

coinflips = np.random.binomial(n = 1, p = .51, size = 1000000)

coinflips

array([0, 0, 0, ..., 1, 1, 0])

### The T-Test Process: The Null and Alternative Hypotheses and the Confidence Level

1) Null Hypothesis: This is a fair coin

$\mu = \bar{x}$


2) Alternative Hypothesis: This is not a fair coin

$\mu \neq \bar{x}$


3) Confidence Level:
How likely does my alternative hypothesis have to be in order for me to reject the null hypothesis?

How willing am I to be incorrect by randomness of the samples 

95% usually use this

99% If something matters a lot (imagine pharmaceuticals) 


We either reject the Null hypothesis or Fail to reject the null hypothesis. We never accept the alternative. We are not saying that we accept the null.  


### Sample (Latin Characters)
$\bar{x}$ = Sample Mean

$s$ = Sample Standard Deviation

$n$ = Sample Size

### Population (Greek Characters)
$\mu$ = Population Mean

$\sigma$ = Population Standard Deviation



In [ ]:
#Run one sample t-test
from scipy import stats

In [ ]:
np.random.seed(42)

coinflips = np.random.binomial(n=1, p=.5, size = 10)

coinflips

array([0, 1, 1, 1, 0, 0, 0, 1, 1, 1])

In [ ]:
coinflips = np.random.binomial(n=1, p=.5, size = 10)

coinflips

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [ ]:
coinflips.mean()

coinflips

array([0, 0, 1, 1, 1, 0, 1, 1, 0, 0])

In [ ]:
#Let's use a toll called a t-test to test if this is a fair coin or not
stats.ttest_1samp(a = coinflips, popmean= .5)


Ttest_1sampResult(statistic=0.0, pvalue=1.0)

p-value is: The probability of the null being true, given the sample that we have collected

Confidence level: How likely does my alternative hypothesis have to be in order for me to reject the null

P-value threshold: .05 (1-confidence level)

If P-value is <.05, I reject the null hypothesis

If P-Value >=.05 I fail to reject the null hypothesis

Conclusion: Based on a t-statistic of 1.309 and a p-value of .22, I fail to reject the null hypothesis that this is a fair coin. 

## Two Sample T-test

Comparing two groups or samples against each other rather than a single sample against a population. 



Ever thought about how long it takes to make a pancake? Have you ever compared the tooking time of a pancake on each eye of your stove? Is the cooking time different between the different eyes? Now, we can run an experiment and collect a sample of 1,000 pancakes on one eye and another 800 pancakes on the other eye. Assumed we used the same pan, batter, and technique on both eyes. Our average cooking times were 180 (5 std) and 178.5 (4.25 std) seconds repsectively. Now, we can tell those numbers are not identicial, but how confident are we that those numbers are practically the same? How do we know the slight difference isn't caused by some external randomness?

Yes, today's lesson will help you figure out how long to cook your pancakes (*theoretically*). Experimentation is up to you; otherwise, you have to accept my data as true. How are going to accomplish this? With probability, statistics, inference and maple syrup (optional). 

<img src="https://images.unsplash.com/photo-1541288097308-7b8e3f58c4c6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=3300&q=80" width=400>



## Lets Practice more 1-sample and 2-sample T-tests

Using the dataset that you will be using on your assignment

In [ ]:
# Let's do it!
xbar1= 180 
s1 = 5

xbar2= 178.5 
s2 = 4.25

sample1 = np.random.normal(xbar1, s1, 1000)

sample2 = np.random.normal(xbar2, s2, 1000)

#Do they look different? Are they different enough?



1) Null Hypothesis: The two burners are the same

$\mu  = \mu$ 


2) Alternative hypothesis: The burners are different

$\mu  \neq \mu$ 


3) confidence interval of 95% 

(5% of the time, our sample might give us the wrong answer)

In [ ]:
#independent two sample t-test
stats.ttest_ind(sample1, sample2)

Ttest_indResult(statistic=5.238736672312338, pvalue=1.787038543518661e-07)

Based on a t-statistic of 5.23 and a pvalue of .000000178 , I reject the null hypothesis that the two burners have the same mean.  

## Student's T Test

>Assuming data come from a Normal distribution, the t test provides a way to test whether the sample mean (that is the mean calculated from the data) is a good estimate of the population mean. 

The derivation of the t-distribution was first published in 1908 by William Gosset while working for the Guinness Brewery in Dublin. Due to proprietary issues, he had to publish under a pseudonym, and so he used the name Student.

The t-distribution is essentially a distribution of means of normaly distributed data. When we use a t-statistic, we are  checking that a mean fails within a certain $\alpha$ probability of the mean of means.

# Resources

- https://homepage.divms.uiowa.edu/~mbognar/applets/t.html
- https://rpsychologist.com/d3/tdist/
- https://gallery.shinyapps.io/tdist/
- https://en.wikipedia.org/wiki/Standard_deviation#Sample_standard_deviation_of_metabolic_rate_of_northern_fulmars
- https://www.khanacademy.org/math/ap-statistics/two-sample-inference/two-sample-t-test-means/v/two-sample-t-test-for-difference-of-means